site_name:  API Dokümantasyonu
site_description: DijitalBelge External API entegrasyon rehberi


theme:
  name: material
  language: tr
  logo: assets/dark-logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Genel Bakış: index.md
  - Kimlik Doğrulama: authentication.md
  - Yetkiler: scopes.md
  - Signers API: signers.md
  - Hatalar: errors.md
  - Örnekler:
      - Curl: examples/curl.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search