#site_name:  API Dokümantasyonu
site_description: DijitalBelge External API entegrasyon rehberi
site_name: DijitalBelge API Dokümantasyon
site_url: https://dokuman.dijitalbelge.com


theme:
  name: material
  language: tr
  logo: assets/dark-logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Genel Bakış: index.md
  - Kimlik Doğrulama: authentication.md
  - Yetkiler: scopes.md    
  - İmzalama Türleri: signature-types.md
  - Bulut İmzalama (Autosign): autosign.md
  - Referans API: reference-api.md
  - İmzacı API: signers.md
  - Dosya İmzalama:
      - Süreç API: progress.md
      - Döküman API: documents.md
  - Taslaktan Süreç API: progress_doctype.md
  - E-İmza Login API: esign.md
  - Mobil İmza Login API: mobilsign.md
  - Sumen API: sumen-api.md
  - Webhook: webhook.md
  - Hatalar: errors.md
  - Örnekler:
      - Abonelik Sözleşmesi İmzalama: examples/abonelik-sozlesmesi.md
      - Karşılıklı Elektronik Sözleşme İmzalama: examples/karsilikli-sozlesme-imzalama.md
extra_css:
  - assets/extra.css

extra:
  analytics:
    provider: google
    property: G-Z4PJ77FKJD


markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight


plugins:
  - search
 
