server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Ana site
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sitemap → cache kapalı
    location = /sitemap.xml {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Robots.txt
    location = /robots.txt {
        add_header Cache-Control "no-cache";
    }

    # Gzip (SEO + performans)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;
}
