name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: copy main version
        run: |
          mkdir -p /dijitalbelge/dokuman
          cp -r * /dijitalbelge/dokuman
      - name: docker up
        working-directory: /dijitalbelge/dokuman
        run: |
          docker compose up -d --build



